export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_ERROR = "GET_STATUS_ERROR";

export const GET_LAYOUT_REQUEST = "GET_LAYOUT_REQUEST";
export const GET_LAYOUT_SUCCESS = "GET_LAYOUT_SUCCESS";
export const GET_LAYOUT_ERROR = "GET_LAYOUT_ERROR";

export const SET_SERVICE_REQUEST = "SET_SERVICE_REQUEST";
export const SET_SERVICE_SUCCESS = "SET_SERVICE_SUCCESS";