# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOn', models.BooleanField(default=True)),
                ('brightness', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('toggle', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
